# Generated by Django 2.0.5 on 2018-05-17 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20180514_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Member', verbose_name='文章'),
        ),
    ]
