# Generated by Django 2.0.5 on 2018-06-06 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20180525_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='新闻标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('editor', models.CharField(default='', max_length=20, verbose_name='编辑人')),
            ],
        ),
        migrations.CreateModel(
            name='News_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='image_error', max_length=20, verbose_name='图片名称')),
                ('filepath', models.CharField(default='media/image/error.png', max_length=50, verbose_name='图片路径')),
                ('image', models.ImageField(upload_to='image/news', verbose_name='图片')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(blank=True, help_text='可选项，若为空格则摘取正文前54个字符', max_length=54, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_modified_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
    ]
