# Generated by Django 2.0.5 on 2018-06-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20180606_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='成果标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('editor', models.CharField(default='', max_length=20, verbose_name='编辑人')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='image_default', max_length=20, verbose_name='图片名称')),
                ('filepath', models.CharField(default='/media/image/achievement/', max_length=50, verbose_name='图片路径')),
                ('image', models.ImageField(upload_to='image/achievement', verbose_name='图片')),
            ],
        ),
        migrations.AlterField(
            model_name='news_image',
            name='filename',
            field=models.CharField(default='image_default', max_length=20, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='news_image',
            name='filepath',
            field=models.CharField(default='/media/image/news/', max_length=50, verbose_name='图片路径'),
        ),
    ]
